site_name: Socle Documentation
pages:
- Overview: index.md
- CLI: model.md
- Source Configuration: source-configuration.md
theme:
  repo_url: https://github.com/thomas10-10/SOCLE
  edit_uri: https://github.com/thomas10-10/socle-documentation/docs
  logo: material/square
  name: material
  features:
    - toc.integrate
  palette: 
    - media: "&quot;(prefers-color-scheme: light)&quot;"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "&quot;(prefers-color-scheme: dark)&quot;"
      scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

