site_name: "SOCLE-DOCUMENTATION"
repo_url: https://github.com/thomas10-10/SOCLE
repo_name: thomas10-10/socle
edit_uri: https://github.com/thomas10-10/socle-documentation/blob/master/docs
pages:
- Overview: index.md
- Get Started: start.md
- CLI: cli.md
- Configuration: configuration.md
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - meta
theme:
  name: material
  features:
    - toc.integrate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs.sticky
  #logo: material/square
    
  palette:
    - media: "&quot;(prefers-color-scheme: light)&quot;"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "&quot;(prefers-color-scheme: dark)&quot;"
      scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

