site_name: Socle Documentation
repo_url: https://github.com/thomas10-10/SOCLE
repo_name: thomas10-10/socle
edit_uri: https://github.com/thomas10-10/socle-documentation/blob/master/docs
pages:
- Overview: index.md
- CLI: model.md
- Source Configuration: source-configuration.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: material/square
  features:
    - toc.integrate
  palette:
    - media: "&quot;(prefers-color-scheme: light)&quot;"
      scheme: youtube
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "&quot;(prefers-color-scheme: dark)&quot;"
      scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

